In [38]:
import pandas as pd

df = pd.read_csv('Galaxy.csv')

In [39]:
df

,data_pid,location,price,time,title,month,brand,series,model,storage
0,274931154,지역정보 없음,190000,2024-06-24 20:07:57,갤럭시s10 5g 256gb 수원인근 집앞까지 가져다드림,64,삼성,갤럭시 S10,regular,256
1,273826430,서울특별시 성북구 동선동,110000,2024-06-24 20:04:57,갤럭시s10 5g 256 잔상폰 팝니다,64,삼성,갤럭시 S10,regular,256
2,242900756,경기도 부천시 원미1동,165000,2024-06-24 19:49:57,갤럭시s10 5g 256기가 팝니다,64,삼성,갤럭시 S10,regular,256
3,274924430,지역정보 없음,190000,2024-06-24 19:39:57,갤럭시s10 5g 256gb 수원인근 집앞까지 가져다드림,64,삼성,갤럭시 S10,regular,256
4,274919870,지역정보 없음,133000,2024-06-24 19:23:57,lg 갤럭시s10 블랙 128g 판매합니다,64,삼성,갤럭시 S10,regular,128
...,...,...,...,...,...,...,...,...,...,...
13311,262903675,경기도 양주시 옥정2동,1150000,2024-05-25 20:09:34,자급제 s24 플러스 512gb 오닉스블랙 미개봉 새상품 판매합니다.,6,삼성,갤럭시 S24,plus,512
13312,257516757,전라북도 익산시 오산면,1410000,2024-04-25 20:09:34,s24울트라 블랙 _512g 단순개봉,6,삼성,갤럭시 S24,Ultra,512
13313,258048001,경기도 고양시 덕양구 흥도동,1480000,2024-04-25 20:09:34,s24 울트라 512 자급제 미개봉,6,삼성,갤럭시 S24,Ultra,512
13314,259695644,서울특별시 성동구 왕십리도선동,1450000,2024-04-25 20:09:34,s24 울트라 512g 블랙 자급제미개봉 급정리,6,삼성,갤럭시 S24,Ultra,512
13315,258759155,경기도 수원시 권선구 구운동,1400000,2024-04-25 20:09:34,[미개봉/자급제] s24울트라 256 티타늄 그레이,6,삼성,갤럭시 S24,Ultra,256

In [40]:
df['price'].max()

np.int64(999999999)

In [41]:
df = df[~df['title'].str.contains('교환')]
df = df[~df['title'].str.contains('매입')]
df = df[~df['title'].str.contains('도매')]
df = df[~df['title'].str.contains('부품용')]
df = df[~df['title'].str.contains('대여')]

In [42]:
idx = df[df['location']=='지역정보 없음'].index
df.drop(idx, axis=0, inplace=True)
df.to_csv('test.csv',index=False, encoding="utf-8-sig")

In [43]:
df=pd.read_csv('test.csv')
df

,data_pid,location,price,time,title,month,brand,series,model,storage
0,273826430,서울특별시 성북구 동선동,110000,2024-06-24 20:04:57,갤럭시s10 5g 256 잔상폰 팝니다,64,삼성,갤럭시 S10,regular,256
1,242900756,경기도 부천시 원미1동,165000,2024-06-24 19:49:57,갤럭시s10 5g 256기가 팝니다,64,삼성,갤럭시 S10,regular,256
2,274918206,서울특별시 금천구 가산동,140000,2024-06-24 19:23:57,*정상특가* 갤럭시s105g 256기가 5091828,64,삼성,갤럭시 S10,regular,256
3,271008580,인천광역시 남구 주안1동,110000,2024-06-24 19:23:57,갤럭시s10 128기가 그린 *가성비굿굿~/#88406,64,삼성,갤럭시 S10,regular,128
4,274903662,서울특별시 금천구 가산동,125000,2024-06-24 18:23:57,*특가처분* 갤럭시s10플러스 128기가 1384215,64,삼성,갤럭시 S10,plus,128
...,...,...,...,...,...,...,...,...,...,...
7556,262903675,경기도 양주시 옥정2동,1150000,2024-05-25 20:09:34,자급제 s24 플러스 512gb 오닉스블랙 미개봉 새상품 판매합니다.,6,삼성,갤럭시 S24,plus,512
7557,257516757,전라북도 익산시 오산면,1410000,2024-04-25 20:09:34,s24울트라 블랙 _512g 단순개봉,6,삼성,갤럭시 S24,Ultra,512
7558,258048001,경기도 고양시 덕양구 흥도동,1480000,2024-04-25 20:09:34,s24 울트라 512 자급제 미개봉,6,삼성,갤럭시 S24,Ultra,512
7559,259695644,서울특별시 성동구 왕십리도선동,1450000,2024-04-25 20:09:34,s24 울트라 512g 블랙 자급제미개봉 급정리,6,삼성,갤럭시 S24,Ultra,512
7560,258759155,경기도 수원시 권선구 구운동,1400000,2024-04-25 20:09:34,[미개봉/자급제] s24울트라 256 티타늄 그레이,6,삼성,갤럭시 S24,Ultra,256

In [59]:
df[df['price']==df['price'].max()]

,data_pid,location,price,time,title,month,brand,series,model,storage
7299,260652240,서울특별시 강서구 화곡본동,1950000,2024-04-25 20:09:24,갤럭시s24플러스 자급제 256 바이올렛,6,삼성,갤럭시 S24,plus,256

In [57]:
df['price'].max()

np.int64(1950000)

In [56]:
idx = df[df['price']==df['price'].max()].index
df.drop(idx, axis=0, inplace=True)

In [60]:
df

,data_pid,location,price,time,title,month,brand,series,model,storage
0,273826430,서울특별시 성북구 동선동,110000,2024-06-24 20:04:57,갤럭시s10 5g 256 잔상폰 팝니다,64,삼성,갤럭시 S10,regular,256
1,242900756,경기도 부천시 원미1동,165000,2024-06-24 19:49:57,갤럭시s10 5g 256기가 팝니다,64,삼성,갤럭시 S10,regular,256
2,274918206,서울특별시 금천구 가산동,140000,2024-06-24 19:23:57,*정상특가* 갤럭시s105g 256기가 5091828,64,삼성,갤럭시 S10,regular,256
3,271008580,인천광역시 남구 주안1동,110000,2024-06-24 19:23:57,갤럭시s10 128기가 그린 *가성비굿굿~/#88406,64,삼성,갤럭시 S10,regular,128
4,274903662,서울특별시 금천구 가산동,125000,2024-06-24 18:23:57,*특가처분* 갤럭시s10플러스 128기가 1384215,64,삼성,갤럭시 S10,plus,128
...,...,...,...,...,...,...,...,...,...,...
7556,262903675,경기도 양주시 옥정2동,1150000,2024-05-25 20:09:34,자급제 s24 플러스 512gb 오닉스블랙 미개봉 새상품 판매합니다.,6,삼성,갤럭시 S24,plus,512
7557,257516757,전라북도 익산시 오산면,1410000,2024-04-25 20:09:34,s24울트라 블랙 _512g 단순개봉,6,삼성,갤럭시 S24,Ultra,512
7558,258048001,경기도 고양시 덕양구 흥도동,1480000,2024-04-25 20:09:34,s24 울트라 512 자급제 미개봉,6,삼성,갤럭시 S24,Ultra,512
7559,259695644,서울특별시 성동구 왕십리도선동,1450000,2024-04-25 20:09:34,s24 울트라 512g 블랙 자급제미개봉 급정리,6,삼성,갤럭시 S24,Ultra,512
7560,258759155,경기도 수원시 권선구 구운동,1400000,2024-04-25 20:09:34,[미개봉/자급제] s24울트라 256 티타늄 그레이,6,삼성,갤럭시 S24,Ultra,256

In [ ]:
df.to_csv('Galaxy_최종.csv',index=False, encoding="utf-8-sig")

In [37]:
s10 = df[df['series']=='갤럭시 S24']
s10

,data_pid,location,price,time,title,month,brand,series,model,storage
6443,258889037,광주광역시 북구 운암1동,40000,2024-06-24 20:01:20,갤럭시 s24 울트라 512gb 대여 합니다 (직거래 광주),6,삼성,갤럭시 S24,Ultra,512
6444,274916888,부산광역시 동래구 사직제3동,800000,2024-06-24 19:08:20,겔럭시s24 256gb 미사용 단순개봉,6,삼성,갤럭시 S24,regular,256
6445,274543144,경상북도 구미시 양포동,900000,2024-06-24 19:08:20,갤럭시s24플러스 256팬텀블랙 판매합니다,6,삼성,갤럭시 S24,plus,256
6446,274607524,부산광역시 동구 좌천동,950000,2024-06-24 19:08:20,[택포 95/네고o] 갤럭시s24 256g + 버즈2,6,삼성,갤럭시 S24,regular,256
6447,270364608,인천광역시 부평구 갈산1동,1420000,2024-06-24 19:08:20,갤럭시s24울트라 512 그레이 자급제 미개봉,6,삼성,갤럭시 S24,Ultra,512
...,...,...,...,...,...,...,...,...,...,...
7565,262903675,경기도 양주시 옥정2동,1150000,2024-05-25 20:09:34,자급제 s24 플러스 512gb 오닉스블랙 미개봉 새상품 판매합니다.,6,삼성,갤럭시 S24,plus,512
7566,257516757,전라북도 익산시 오산면,1410000,2024-04-25 20:09:34,s24울트라 블랙 _512g 단순개봉,6,삼성,갤럭시 S24,Ultra,512
7567,258048001,경기도 고양시 덕양구 흥도동,1480000,2024-04-25 20:09:34,s24 울트라 512 자급제 미개봉,6,삼성,갤럭시 S24,Ultra,512
7568,259695644,서울특별시 성동구 왕십리도선동,1450000,2024-04-25 20:09:34,s24 울트라 512g 블랙 자급제미개봉 급정리,6,삼성,갤럭시 S24,Ultra,512
7569,258759155,경기도 수원시 권선구 구운동,1400000,2024-04-25 20:09:34,[미개봉/자급제] s24울트라 256 티타늄 그레이,6,삼성,갤럭시 S24,Ultra,256