In [1]:
#오라클 연결 설정
import cx_Oracle

cx_Oracle.init_oracle_client(lib_dir=r"C:\Users\Administrator\Downloads\instantclient-basic-windows.x64-23.4.0.24.05\instantclient_23_4")

In [2]:
connection = cx_Oracle.connect(user='ADMIN', password='T3tkdguqxlavmfhwprxm', dsn='t3gp1_medium')

In [3]:
cur = connection.cursor()

In [ ]:
# connection.close()

In [16]:
#로우데이터 검색후 저장
import pandas as pd
import requests
import json
import time
import datetime
import os
from pprint import pprint

columns = ['category_id', 'name', 'product_image', 'pid', 'price', 'update_time', 'location']
df=pd.DataFrame(columns=columns)
# API URL
input_list = ['아이폰 x', '아이폰 11','아이폰 12','아이폰 13','아이폰 14','아이폰15','아이폰']
for input_query in input_list:
    for i in range(100):
        try:
            url = f'https://api.bunjang.co.kr/api/1/find_v2.json?q={input_query}&order=score&page={i}&request_id=2024704081724&f_category_id=600700001&stat_device=w&n=100&stat_category_required=1&req_ref=search&version=5'
            time.sleep(0.5)
            # Request API
            response = requests.get(url)
            data = response.json()

            
            
            ipdf = pd.DataFrame(data['list'])[columns]
            df = pd.concat([df, ipdf],ignore_index=True)
        except:
            break

C:\Users\Administrator\AppData\Local\Temp\ipykernel_3192\4213418496.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, ipdf],ignore_index=True)

In [18]:
df=df.dropna()
df

,category_id,name,product_image,pid,price,update_time,location
0,600700001,삽니다)아이폰11 아이폰12프로 아이폰13 아이폰14 XS X 매입합니다,https://media.bunjang.co.kr/product/85739178_1...,85739178,740000,1.720674e+09,대구광역시 중구 성내1동
1,600700001,액정/외관깨끗 아이폰X 배터리성능 100% 블랙 64GB 25937,https://media.bunjang.co.kr/product/278962084_...,278962084,264000,1.720683e+09,경상남도 양산시 양주동
2,600700001,아이폰 x이상 xs xr 12mini se3 se2 대량판매,https://media.bunjang.co.kr/product/278960577_...,278960577,150000,1.720683e+09,
3,600700001,아이폰x 256 공기계 스그팝니다,https://media.bunjang.co.kr/product/275338127_...,275338127,200000,1.720680e+09,경기도 평택시 팽성읍
5,600700001,"모든 중고폰 삽니다. 파손폰 아이폰 갤럭시 x, xs 등",https://media.bunjang.co.kr/product/271350956_...,271350956,555555,1.720680e+09,대구광역시 달서구 신당동
...,...,...,...,...,...,...,...
53634,600700001,아이폰SE1 실버 판매,https://media.bunjang.co.kr/product/259700337_...,259700337,108000,1.716619e+09,
53635,600700001,파손폰 고장폰 부품폰 아이폰15 아이폰14 아이폰13 아이폰12,https://media.bunjang.co.kr/product/196357088_...,196357088,987000,1.685668e+09,인천광역시 부평구 부평1동
53636,600700001,아이폰12pro 128기가 그래파이트 판매합니다,https://media.bunjang.co.kr/product/268134317_...,268134317,300000,1.717246e+09,
53637,600700001,아이폰 12 퍼플 128GB 특S급,https://media.bunjang.co.kr/product/263639987_...,263639987,425000,1.716775e+09,서울특별시 금천구 가산동
53638,600700001,아이폰se1,https://media.bunjang.co.kr/product/264204411_...,264204411,160000,1.716294e+09,

In [19]:
df_list = df.values.tolist()

cur.executemany("INSERT INTO THUNDER_IPHON_LOW (CATEGORY_ID, NAME, PRODUCT_IMAGE, PID, PRICE, UPDATE_TIME, LOCATION) VALUES (:1,:2,:3,:4,:5,:6,:7)",
            df_list, batcherrors = True)

In [20]:
datas = pd.read_sql(sql="select * from THUNDER_IPHON_LOW", con = connection)
datas

C:\Users\Administrator\AppData\Local\Temp\ipykernel_3192\987040108.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  datas = pd.read_sql(sql="select * from THUNDER_IPHON_LOW", con = connection)

,CATEGORY_ID,NAME,PRODUCT_IMAGE,PID,PRICE,UPDATE_TIME,LOCATION
0,600700001,아이폰x 급처,https://media.bunjang.co.kr/product/278843275_...,278843275,130000,1720638753,경기도 부천시 원미2동
1,600700001,아이폰X 64기가,https://media.bunjang.co.kr/product/278871137_...,278871137,80000,1720624977,None
2,600700001,"아이폰6S Plus -> 아이폰 X, se 시리즈",https://media.bunjang.co.kr/product/278798938_...,278798938,150000,1720602308,None
3,600700001,(급처) 아이폰 X 256GB 실버,https://media.bunjang.co.kr/product/278855585_...,278855585,130000,1720619382,경기도 성남시 분당구 서현1동
4,600700001,아이폰X 실버 256GB 부산 중고폰 팝니다 28443,https://media.bunjang.co.kr/product/278820985_...,278820985,322000,1720609242,None
...,...,...,...,...,...,...,...
53416,600700001,아이폰 6s 로즈골드,https://media.bunjang.co.kr/product/260821494_...,260821494,160000,1716507165,None
53417,600700001,아이폰se 전색상 용량 ss급 배터리 100%,https://media.bunjang.co.kr/product/205794792_...,205794792,159000,1679612400,경기도 고양시 일산동구 백석2동
53418,600700001,아이폰 14pro 무음 256,https://media.bunjang.co.kr/product/236196492_...,236196492,1450000,1716652101,부산광역시 해운대구 우제2동
53419,600700001,아이폰8플러스 256G 무잔상 상태굿 ^^,https://media.bunjang.co.kr/product/259306160_...,259306160,180000,1717127732,인천광역시 계양구 작전2동
53420,600700001,아이폰15프로,https://media.bunjang.co.kr/product/264243418_...,264243418,1050000,1716341229,서울특별시 성북구 월곡제1동

In [21]:
cur.execute("commit")

In [22]:
#로우데이터 검색후 저장
import pandas as pd
import requests
import json
import time
import datetime
import os
from pprint import pprint

columns = ['category_id', 'name', 'product_image', 'pid', 'price', 'update_time', 'location']
df=pd.DataFrame(columns=columns)
# API URL
input_list = ['갤럭시 s10', '갤럭시 s20','갤럭시 s21','갤럭시 s22','갤럭시 s23','갤럭시 s24','갤럭시']
for input_query in input_list:
    for i in range(100):
        try:
            url = f'https://api.bunjang.co.kr/api/1/find_v2.json?q={input_query}&order=score&page={i}&request_id=2024704081724&f_category_id=600700001&stat_device=w&n=100&stat_category_required=1&req_ref=search&version=5'
            time.sleep(1)
            # Request API
            response = requests.get(url)
            data = response.json()

            
            
            ipdf = pd.DataFrame(data['list'])[columns]
            df = pd.concat([df, ipdf],ignore_index=True)
        except:
            break

C:\Users\Administrator\AppData\Local\Temp\ipykernel_3192\2086486927.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, ipdf],ignore_index=True)

In [23]:
df

,category_id,name,product_image,pid,price,update_time,location
0,600700001,갤럭시s10 5g a급 초특가 기능이상없음!,https://media.bunjang.co.kr/product/278962908_...,278962908,193000,1.720684e+09,인천광역시 서구 가정1동
1,600700001,18791 갤럭시S10 5G(G977) 256기가 실버 무잔상 정상해지,https://media.bunjang.co.kr/product/278958883_...,278958883,190000,1.720682e+09,경기도 수원시 팔달구 인계동
2,600700001,[업무용공기계특가]갤럭시S10 5G 깔끔한 가성비굿,https://media.bunjang.co.kr/product/278956623_...,278956623,190000,1.720682e+09,
3,600700001,#할인가능 갤럭시S10E 128GB 화이트 (무잔상) / 0611,https://media.bunjang.co.kr/product/271597372_...,271597372,135000,1.720682e+09,경기도 평택시 신장2동
4,NaN,삼성 갤럭시 S10 S10플러스 S10 5G 256GB S10E 중고 중고폰 공기계,NaN,NaN,152000,NaN,NaN
...,...,...,...,...,...,...,...
44722,600700001,[새폰급]삼성중고폰특가[갤럭시S23 정품할인판매],https://media.bunjang.co.kr/product/278220525_...,278220525,599000,1.720386e+09,경기도 김포시 풍무동
44723,600700001,갤럭시S21 5G 256GB 수원인근 집앞까지 가져다드림,https://media.bunjang.co.kr/product/278217400_...,278217400,250000,1.720381e+09,
44724,600700001,8갤럭시S21싸게팝니다기능성능이상없어요 중고폰,https://media.bunjang.co.kr/product/278219601_...,278219601,219000,1.720385e+09,경기도 김포시 풍무동
44725,600700001,1갤럭시S10 128G무잔상 중고폰 싸게팝니다 상태굿,https://media.bunjang.co.kr/product/278096506_...,278096506,215000,1.720343e+09,경기도 김포시 풍무동
44726,600700001,8갤럭시S21싸게팝니다기능성능이상없어요 중고폰,https://media.bunjang.co.kr/product/278092460_...,278092460,219000,1.720342e+09,경기도 김포시 풍무동

In [24]:
df=df.dropna()
df

,category_id,name,product_image,pid,price,update_time,location
0,600700001,갤럭시s10 5g a급 초특가 기능이상없음!,https://media.bunjang.co.kr/product/278962908_...,278962908,193000,1.720684e+09,인천광역시 서구 가정1동
1,600700001,18791 갤럭시S10 5G(G977) 256기가 실버 무잔상 정상해지,https://media.bunjang.co.kr/product/278958883_...,278958883,190000,1.720682e+09,경기도 수원시 팔달구 인계동
2,600700001,[업무용공기계특가]갤럭시S10 5G 깔끔한 가성비굿,https://media.bunjang.co.kr/product/278956623_...,278956623,190000,1.720682e+09,
3,600700001,#할인가능 갤럭시S10E 128GB 화이트 (무잔상) / 0611,https://media.bunjang.co.kr/product/271597372_...,271597372,135000,1.720682e+09,경기도 평택시 신장2동
5,600700001,갤럭시 S10E,https://media.bunjang.co.kr/product/275315659_...,275315659,130000,1.720682e+09,
...,...,...,...,...,...,...,...
44722,600700001,[새폰급]삼성중고폰특가[갤럭시S23 정품할인판매],https://media.bunjang.co.kr/product/278220525_...,278220525,599000,1.720386e+09,경기도 김포시 풍무동
44723,600700001,갤럭시S21 5G 256GB 수원인근 집앞까지 가져다드림,https://media.bunjang.co.kr/product/278217400_...,278217400,250000,1.720381e+09,
44724,600700001,8갤럭시S21싸게팝니다기능성능이상없어요 중고폰,https://media.bunjang.co.kr/product/278219601_...,278219601,219000,1.720385e+09,경기도 김포시 풍무동
44725,600700001,1갤럭시S10 128G무잔상 중고폰 싸게팝니다 상태굿,https://media.bunjang.co.kr/product/278096506_...,278096506,215000,1.720343e+09,경기도 김포시 풍무동
44726,600700001,8갤럭시S21싸게팝니다기능성능이상없어요 중고폰,https://media.bunjang.co.kr/product/278092460_...,278092460,219000,1.720342e+09,경기도 김포시 풍무동

In [27]:
df_list = df.values.tolist()

cur.executemany("INSERT INTO THUNDER_GALAXY_LOW (CATEGORY_ID, NAME, PRODUCT_IMAGE, PID, PRICE, UPDATE_TIME, LOCATION) VALUES (:1,:2,:3,:4,:5,:6,:7)",
            df_list, batcherrors = True)

In [28]:
datas = pd.read_sql(sql="select * from THUNDER_GALAXY_LOW", con = connection)
datas

C:\Users\Administrator\AppData\Local\Temp\ipykernel_3192\863659746.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  datas = pd.read_sql(sql="select * from THUNDER_GALAXY_LOW", con = connection)

,CATEGORY_ID,NAME,PRODUCT_IMAGE,PID,PRICE,UPDATE_TIME,LOCATION
0,600700001,액정/외관깨끗 갤럭시S10 (G973) 화이트 128GB 판매 10622,https://media.bunjang.co.kr/product/278917793_...,278917793,187000,1720667508,울산광역시 남구 삼산동
1,600700001,갤럭시 S10 플라밍고핑크 128기가 A급 팝니다.,https://media.bunjang.co.kr/product/139683696_...,139683696,180000,1720672065,None
2,600700001,193693 KT 갤럭시S10 LTE 화이트 외관깨끗 128GB 무잔상,https://media.bunjang.co.kr/product/276670882_...,276670882,144000,1720671444,경기도 부천시 중3동
3,600700001,삼성 갤럭시s10플러스 512GB 화이트 S급 순천/여수/광양 중고폰,https://media.bunjang.co.kr/product/258815146_...,258815146,240000,1720671866,전라남도 순천시 삼산동
4,600700001,갤럭시 S10플러스 플라밍고 핑크 128기가 A급 팔아요~,https://media.bunjang.co.kr/product/273365545_...,273365545,210000,1720671459,부산광역시 남구 대연제1동
...,...,...,...,...,...,...,...
44511,600700001,A급)무잔상 갤럭시 노트20울트라 256G 블랙 부산,https://media.bunjang.co.kr/product/260772842_...,260772842,385000,1720507570,부산광역시 부산진구 전포제2동
44512,600700001,액정/외관깨끗 갤럭시S22+ (S906) 그린 256GB 22849,https://media.bunjang.co.kr/product/278588091_...,278588091,418000,1720508291,None
44513,600700001,갤럭시 와이드6블랙 무잔상 A급 정상공기계,https://media.bunjang.co.kr/product/278493280_...,278493280,110000,1720505214,경기도 화성시 봉담읍
44514,600700001,갤럭시 A34 어썸 바이올렛 무잔상 정상공기계,https://media.bunjang.co.kr/product/278216580_...,278216580,260000,1720505063,경기도 수원시 장안구 영화동
44515,600700001,갤럭시 S20플러스 레드 A급 무잔상 정상공기계,https://media.bunjang.co.kr/product/278505556_...,278505556,250000,1720505214,경기도 화성시 봉담읍

In [32]:
cur.execute("COMMIT")

In [33]:
connection.close()

In [7]:
import requests
import re
import json
import urllib.parse
import pandas as pd

columns = [
                    "PID",
                    "PRICE",
                    "PRODUCT_IMAGE",
                    "NAME",
                    "DATE",
                    "LOCATION",
                    "DESCRIPTION",
                    "DELTA_TIME",
                ]
df=pd.DataFrame(columns=columns)

def fetch_latest_hash():
    url = "https://web.joongna.com/"
    try:
        response = requests.get(url)
        response.raise_for_status()
        match = re.search(r"/_next/static/([^/]+)/_ssgManifest\.js", response.text)
        if match:
            return match.group(1)
        else:
            print("해시 값을 찾을 수 없습니다.")
            return None
    except requests.RequestException as e:
        print(f"요청 중 오류 발생: {e}")
        return None


def fetch_product_description(product_seq, hash_value):
    product_url = (
        f"https://web.joongna.com/_next/data/{hash_value}/product/{product_seq}.json"
    )
    try:
        response = requests.get(product_url)
        response.raise_for_status()
        data = response.json()
        product_description = data["pageProps"]["dehydratedState"]["queries"][0][
            "state"
        ]["data"]["data"].get("productDescription")
        return product_description
    except requests.RequestException as e:
        print(f"요청 중 오류 발생: {e}")
    except KeyError as e:
        print(f"JSON 구조에서 키를 찾을 수 없음: {e}")
    except json.JSONDecodeError as e:
        print(f"JSON 디코딩 중 오류 발생: {e}")
    return None


def fetch_joongna_data(keyword, page=1, category=1151):
    latest_hash = fetch_latest_hash()
    if not latest_hash:
        return None

    base_url = f"https://web.joongna.com/_next/data/{latest_hash}/search/"
    encoded_keyword = urllib.parse.quote(keyword)
    url = f"{base_url}{encoded_keyword}.json?keyword={encoded_keyword}&page={page}&category={category}"

    try:
        response = requests.get(url)
        response.raise_for_status()
        data = response.json()
        items = data["pageProps"]["dehydratedState"]["queries"][1]["state"]["data"][
            "data"
        ].get("items", [])

        for item in items:
            product_seq = item.get("seq", None)
            if product_seq:
                product_description = fetch_product_description(
                    product_seq, latest_hash
                )
                item["productDescription"] = product_description

        return items
    except requests.RequestException as e:
        print(f"요청 중 오류 발생: {e}")
    except KeyError as e:
        print(f"JSON 구조에서 키를 찾을 수 없음: {e}")
    except json.JSONDecodeError as e:
        print(f"JSON 디코딩 중 오류 발생: {e}")
    return None


def main():
    keyword_list = ['아이폰 x', '아이폰 11','아이폰 12','아이폰 13','아이폰 14','아이폰15','아이폰']
    category = 1151
    for keyword in keyword_list:
        for page in range(10):
            items = fetch_joongna_data(keyword, page, category)
            if items:
                pac = pd.DataFrame(items)
                print(pac.columns)
                columns = [
                    "seq",
                    "price",
                    "url",
                    "title",
                    "sortDate",
                    "locationNames",
                    "productDescription",
                ]
                pac = pac[columns]
                pac = pac.dropna(subset=["locationNames"])
                # # locationNames 빈 리스트인 경우 삭제
                # df = df[df["locationNames"].map(len) > 0]
                # # locationNames 컬럼에서 첫번째 값만 선택
                # df["locationNames"] = df["locationNames"].apply(lambda x: x[0])
                # # sortDate 컬럼에서 값 없으면 삭제
                pac = pac.dropna(subset=['sortDate'])
                # # sortDate 컬럼에서 datetime 형식으로 변환
                pac["sortDate"] = pd.to_datetime(pac["sortDate"])
                # # time_delta 컬럼 추가
                pac["time_delta"] = pd.Timestamp.now() - pac["sortDate"]
                # # 제거할 키워드
                # df = df[~df['title'].str.contains('교환')]
                # df = df[~df['title'].str.contains('매입')]
                # df = df[~df['title'].str.contains('삽니다')]
                # df = df[~df['title'].str.contains('구합니다')]
                # df = df[~df['title'].str.contains('도매')]
                # df = df[~df['title'].str.contains('대량')]
                # df = df[~df['title'].str.contains('대여')]
                # df = df[~df['title'].str.contains('정리')]
                # df = df[~df['title'].str.contains('수리')]
                # df = df[~df['title'].str.contains('공시')]
                # ['seq', 'price', 'url', 'title', 'sortDate', 'locationNames',
                #'productDescription', 'time_delta']
                pac.columns = [
                    "PID",
                    "PRICE",
                    "PRODUCT_IMAGE",
                    "NAME",
                    "DATE",
                    "LOCATION",
                    "DESCRIPTION",
                    "DELTA_TIME",
                ]
                df = pd.concat([df, pac],ignore_index=True)

            else:
                print("데이터를 가져오지 못했습니다.")


if __name__ == "__main__":
    main()

Index(['seq', 'productPositionNo', 'platformType', 'price', 'url', 'title',
       'state', 'sortDate', 'mainLocationName', 'articleSeq', 'articleUrl',
       'videoProductYn', 'wishCount', 'jnPayBadgeFlag', 'pickupBadgeFlag',
       'highlightedTitle', 'storeSeq', 'locationNames', 'productType', 'tags',
       'objectType', 'productDescription'],
      dtype='object')

UnboundLocalError: local variable 'df' referenced before assignment

In [38]:
df

,category_id,name,product_image,pid,price,update_time,location
0,600700001,갤럭시s10 5g a급 초특가 기능이상없음!,https://media.bunjang.co.kr/product/278962908_...,278962908,193000,1.720684e+09,인천광역시 서구 가정1동
1,600700001,18791 갤럭시S10 5G(G977) 256기가 실버 무잔상 정상해지,https://media.bunjang.co.kr/product/278958883_...,278958883,190000,1.720682e+09,경기도 수원시 팔달구 인계동
2,600700001,[업무용공기계특가]갤럭시S10 5G 깔끔한 가성비굿,https://media.bunjang.co.kr/product/278956623_...,278956623,190000,1.720682e+09,
3,600700001,#할인가능 갤럭시S10E 128GB 화이트 (무잔상) / 0611,https://media.bunjang.co.kr/product/271597372_...,271597372,135000,1.720682e+09,경기도 평택시 신장2동
5,600700001,갤럭시 S10E,https://media.bunjang.co.kr/product/275315659_...,275315659,130000,1.720682e+09,
...,...,...,...,...,...,...,...
44722,600700001,[새폰급]삼성중고폰특가[갤럭시S23 정품할인판매],https://media.bunjang.co.kr/product/278220525_...,278220525,599000,1.720386e+09,경기도 김포시 풍무동
44723,600700001,갤럭시S21 5G 256GB 수원인근 집앞까지 가져다드림,https://media.bunjang.co.kr/product/278217400_...,278217400,250000,1.720381e+09,
44724,600700001,8갤럭시S21싸게팝니다기능성능이상없어요 중고폰,https://media.bunjang.co.kr/product/278219601_...,278219601,219000,1.720385e+09,경기도 김포시 풍무동
44725,600700001,1갤럭시S10 128G무잔상 중고폰 싸게팝니다 상태굿,https://media.bunjang.co.kr/product/278096506_...,278096506,215000,1.720343e+09,경기도 김포시 풍무동
44726,600700001,8갤럭시S21싸게팝니다기능성능이상없어요 중고폰,https://media.bunjang.co.kr/product/278092460_...,278092460,219000,1.720342e+09,경기도 김포시 풍무동